# Generated by Django 5.0.4 on 2024-04-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Resume Name", models.FileField(upload_to="resume/")),
            ],
        ),
        migrations.CreateModel(
            name="HrModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Hr Full Name", models.CharField(max_length=250)),
                ("Hr Address", models.CharField(blank=True, max_length=250, null=True)),
                ("Hr Profile Image", models.ImageField(upload_to="hr_profile/")),
                (
                    "Hr Phone Number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("Hr Join On", models.DateTimeField(auto_now_add=True)),
                (
                    "Hr Username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Candidate Name", models.CharField(max_length=200)),
                ("Candidate Email", models.EmailField(max_length=254)),
                ("Candidate Score", models.IntegerField()),
                ("Candidate Resume Prediction", models.CharField(max_length=200)),
                (
                    "Resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_resume.resume",
                    ),
                ),
            ],
        ),
    ]
