# Generated by Django 5.0.4 on 2024-04-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Full Name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Profile Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Join On",
            new_name="join_on",
        ),
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Phone Number",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="hrmodel",
            old_name="Hr Username",
            new_name="user",
        ),
    ]
