# Generated by Django 5.0.4 on 2024-04-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0002_rename_hr_address_hrmodel_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="Resume Name",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="Candidate Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="Candidate Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="Candidate Resume Prediction",
            new_name="prediction",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="Resume",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="Candidate Score",
            new_name="score",
        ),
    ]
