# Generated by Django 5.0.4 on 2024-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0004_affinemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="phone",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
