# Generated by Django 5.0.4 on 2024-05-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0005_resumeanalysis_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterViewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=250)),
                ("question_text_des", models.TextField()),
                ("question_image", models.FileField(upload_to="interviewer/images")),
                ("question_image_des", models.TextField()),
                (
                    "answer_one",
                    models.CharField(max_length=200, verbose_name="Answer A"),
                ),
                (
                    "answer_two",
                    models.CharField(max_length=200, verbose_name="Answer B"),
                ),
                (
                    "answer_three",
                    models.CharField(max_length=200, verbose_name="Answer C"),
                ),
                (
                    "answer_four",
                    models.CharField(max_length=200, verbose_name="Answer D"),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("job_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="InterviewQuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("user_answer", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_resume.interviewquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employee_resume.job"
            ),
        ),
    ]
