# Generated by Django 5.0.4 on 2024-05-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0008_alter_interviewquestion_question_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewquestionreview",
            name="answer_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="interviewquestionreview",
            name="user_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=5,
                null=True,
            ),
        ),
    ]
