# Generated by Django 5.0.4 on 2024-06-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_resume", "0009_interviewquestionreview_answer_rate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200, verbose_name="Applicant Full Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Applicant Address"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Applicant/Images/", verbose_name="Applicant Image"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Applicant Phone"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applicant User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Applicant",
            },
        ),
    ]
